/**
 * 389. Find the Difference
 * Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 */

package hashing;

public class FindTheDifference {
	
	public static char findDiff(String s, String t)
	{
		//does not work for the input "a, aa"
		/**
		 * 
		 *
		HashMap<Character, Integer> hmap = new HashMap<>();
		char c= '\0';
		//Put the contents of String s in the HashMap
		for(char n: s.toCharArray())
		{
			hmap.put(n, hmap.getOrDefault(n,0) +1);
		}
		//Check if the HashMap has the contents of String t
		//return the character which is not present in s
		for(char n: t.toCharArray())
		{
			if(!hmap.containsKey(n))
			{
				c = n;
			}
		}
		return c;
	*/
		//Concatenate the two strings, and find the odd one out.
		//using Bit Manipulation
		String str = s.concat(t);
		char diffChar = 0;
		for(char c: str.toCharArray())
		{
			diffChar = (char) (diffChar ^ c);
		}
		return diffChar;
		
	}
	public static void main(String[] args)
	{
		String s = "abcd"; 
		
		String t = "abcde";
		System.out.println(findDiff(s,t));
		
		String u = "a";
		String v = "aa";
		System.out.println(findDiff(u,v));
	}

}
